"""empty message

Revision ID: d8571730f82f
Revises: 
Create Date: 2020-05-15 14:30:51.354614

"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = 'd8571730f82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'disease',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=40), nullable=False, unique=True)
    )
    
    op.create_table(
        'disease_state',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=40), nullable=False, unique=True)
    )
    
    op.create_table(
        'role',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=40), nullable=False, unique=True)
    )
    
    op.create_table(
        'state',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=40), nullable=False, unique=True)
    )
    
    op.create_table(
        'patient',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=40), nullable=False, unique=True),
        sa.Column('state', sa.Integer, sa.ForeignKey('state.id'), nullable=False),
        sa.Column('diseaseState', sa.Integer, sa.ForeignKey('disease_state.id'), nullable=False)
    )
    
    op.create_table(
        'user',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('username', sa.String(length=40), nullable=False, unique=True),
        sa.Column('email', sa.String(length=120), nullable=False, unique=True),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('date_created', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('last_update', sa.DateTime(timezone=True), nullable=True, onupdate=sa.func.now()),
        sa.Column('active', sa.Boolean, nullable=True, default=True),
        sa.Column('role', sa.Integer, sa.ForeignKey('role.id'), nullable=False)
    )
    
    op.create_table(
        'disease_patient',
        sa.Column('disease_id', sa.Integer, sa.ForeignKey('disease.id'), primary_key=True),
        sa.Column('patient_id', sa.Integer, sa.ForeignKey('patient.id'), primary_key=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_patient')
    op.drop_table('user')
    op.drop_table('patient')
    op.drop_table('state')
    op.drop_table('role')
    op.drop_table('disease_state')
    op.drop_table('disease')
    # ### end Alembic commands ###
